[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obj2asterix = { path="../crates/obj2asterix" }
spec_parser = { path="../crates/spec_parser" }
serde_json = "1.0"